spring:
  application:
    name: grade-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: H2
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
